# .github/workflows/rebuild-catalog.yml
name: Rebuild experiment catalog (issue trigger)

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issues' && contains(join(fromJson(toJson(github.event.issue.labels)).*.name, ','), 'rebuild-catalog'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install build deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i ajv ajv-formats glob yaml

      - name: Build catalog (experiments.json)
        run: node scripts/indexer.mjs

      - name: Copy site files to public/experiments/
        run: |
          mkdir -p public/experiments
          cp -f experiments/index.html public/experiments/index.html
          if compgen -G "experiments/*/" > /dev/null; then
            cp -a experiments/* public/experiments/
          fi
          cp -f public/experiments.json public/experiments/experiments.json

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  comment:
    if: github.event_name == 'issues'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Comment back on issue (done)
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: '✅ Catalog rebuild triggered. The site will update shortly.'
            });

